### ISSUE TITLE
Several chart tarballs unavailable

### ISSUE THREAD

**Issue by wesjdj** [kanisterio/kanister-charts#1]
Hi,

Since earlier today, I have been unable to pull several charts.

```
helm show chart kanister/profile
Error: failed to fetch https://charts.kanister.io/profile-0.111.0.tgz : 404 Not Found
```

```
helm show chart kanister/kanister-postgresql
Error: failed to fetch https://charts.kanister.io/kanister-postgresql-0.32.0.tgz : 404 Not Found
```

```
helm show chart kanister/kanister-mysql
Error: failed to fetch https://charts.kanister.io/kanister-mysql-0.32.0.tgz : 404 Not Found
```

`kanister-operator`, however, is available.

```
helm show chart kanister/kanister-operator
apiVersion: v1
appVersion: 0.112.0
description: Kanister-operator Helm chart for Kubernetes
home: https://kanister.io/
icon: https://kasten.io/assets/img/kanister-logo.png
maintainers:
- email: ilya@kasten.io
  name: depohmel
- email: tom@kasten.io
  name: tdmanv
name: kanister-operator
version: 0.112.0
```

I have seen some activity in this repo yesterday, could this have caused these issues?

Thanks
